# Generated by Django 4.0.3 on 2022-04-11 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('hash', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Subooru',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Booru_Tag_Pair',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('blacklist', models.BooleanField(default=False)),
                ('booru_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booru.subooru')),
                ('tag_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booru.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Booru_File_Pair',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('blacklist', models.BooleanField(default=False)),
                ('booru_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booru.subooru')),
                ('file_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booru.file')),
            ],
        ),
    ]
