# Generated by Django 4.0.3 on 2022-04-22 21:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('booru', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subooru',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
