# Generated by Django 4.0.3 on 2022-04-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booru', '0002_alter_subooru_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booru_tag_pair',
            name='booru_key',
        ),
        migrations.RemoveField(
            model_name='booru_tag_pair',
            name='tag_key',
        ),
        migrations.AddField(
            model_name='subooru',
            name='files',
            field=models.ManyToManyField(to='booru.file'),
        ),
        migrations.DeleteModel(
            name='Booru_File_Pair',
        ),
        migrations.DeleteModel(
            name='Booru_Tag_Pair',
        ),
    ]
