# Generated by Django 4.0.3 on 2022-04-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booru', '0003_remove_booru_tag_pair_booru_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subooru',
            name='files',
            field=models.ManyToManyField(blank=True, default=None, to='booru.file'),
        ),
    ]
