# Generated by Django 4.0.3 on 2022-04-22 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booru', '0006_alter_subooru_files_alter_subooru_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='id',
            field=models.IntegerField(null=True),
        ),
    ]
